### ISSUE TITLE
FastAPI dependency on Starlette wrong

### ISSUE THREAD

**Issue by erg-samowzbudnik** [pentoo/pentoo-overlay#1095]
starlette-0.18 breaks fastapi
dev-python/fastapi-0.65.2 ebuild states dependency on starlette as >=dev-python/starlette-0.14.2 but they should be limited to no higher than dev-python/starlette-0.17,
ergo they should be set as:
`>=dev-python/starlette-0.14.2`
`<dev-python/starlette-0.18`

**Comment by blshkv** [comment]
Hi, can you post the error?

**Comment by blshkv** [comment]
I tried their test script ```uvicorn main:app --reload```. It works with any starlette version

**Comment by blshkv** [comment]
```
uvicorn  main:app --reload
INFO:     Will watch for changes in these directories: ['/tmp']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [9835] using statreload
INFO:     Started server process [9837]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:41472 - "GET / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/fastapi/applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.10/site-packages/starlette/exceptions.py", line 87, in __call__
    raise exc
  File "/usr/lib/python3.10/site-packages/starlette/exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/lib/python3.10/site-packages/fastapi/routing.py", line 216, in app
    solved_result = await solve_dependencies(
  File "/usr/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 465, in solve_dependencies
    response = response or Response(
  File "/usr/lib/python3.10/site-packages/starlette/responses.py", line 50, in __init__
    self.init_headers(headers)
  File "/usr/lib/python3.10/site-packages/starlette/responses.py", line 77, in init_headers
    and not (self.status_code < 200 or self.status_code in (204, 304))
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by blshkv** [comment]
ok, it does break with 0.18.0. Thanks!

**Comment by erg-samowzbudnik** [comment]
Ups I was way to slow :) glad you could replicate it.
