### ISSUE TITLE
libvshadow_ntfs_volume_header_read issue

### ISSUE THREAD

**Issue by AlexSta2019** [pentoo/pentoo-overlay#1483]
**Description of problem:**

Error while parsing E01 image from Win7 system. The volume offset from the error message seems to be wrong, the image I analyze is much smaller.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dfvfs/resolver/resolver.py", line 163, in OpenFileSystem
    file_system.Open()
  File "/usr/lib/python3/dist-packages/dfvfs/vfs/file_system.py", line 246, in Open
    self._Open(mode=mode)
  File "/usr/lib/python3/dist-packages/dfvfs/vfs/vshadow_file_system.py", line 62, in _Open
    vshadow_volume.open_file_object(file_object)
OSError: pyvshadow_volume_open_file_object: unable to open volume. libvshadow_ntfs_volume_header_read_file_io_handle: unable to read NTFS volume header data at offset: 491320770560 (0x7265000000). libvshadow_volume_open_read_ntfs_volume_headers: unable to read backup NTFS volume header. libvshadow_volume_open_read: unable to read NTFS volume headers. libvshadow_volume_open_file_io_handle: unable to read from file IO handle.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/psteal.py", line 107, in <module>
    if not Main():
  File "/usr/bin/psteal.py", line 83, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python3/dist-packages/plaso/cli/extraction_tool.py", line 716, in ExtractEventsFromSources
    self.ScanSource(self._source_path)
  File "/usr/lib/python3/dist-packages/plaso/cli/storage_media_tool.py", line 648, in ScanSource
    base_path_specs = volume_scanner.GetBasePathSpecs(
  File "/usr/lib/python3/dist-packages/dfvfs/helpers/volume_scanner.py", line 705, in GetBasePathSpecs
    return self._GetBasePathSpecs(scan_context, options)
  File "/usr/lib/python3/dist-packages/plaso/cli/storage_media_tool.py", line 225, in _GetBasePathSpecs
    self._ScanVolume(scan_context, sub_scan_node, options, base_path_specs)
  File "/usr/lib/python3/dist-packages/dfvfs/helpers/volume_scanner.py", line 625, in _ScanVolume
    self._ScanVolume(scan_context, sub_scan_node, options, base_path_specs)
  File "/usr/lib/python3/dist-packages/dfvfs/helpers/volume_scanner.py", line 600, in _ScanVolume
    self._ScanVolumeSystemRoot(
  File "/usr/lib/python3/dist-packages/plaso/cli/storage_media_tool.py", line 312, in _ScanVolumeSystemRoot
    volume_system.Open(scan_node.path_spec)
  File "/usr/lib/python3/dist-packages/dfvfs/volume/volume_system.py", line 290, in Open
    self._file_system = resolver.Resolver.OpenFileSystem(path_spec)
  File "/usr/lib/python3/dist-packages/dfvfs/resolver/resolver.py", line 165, in OpenFileSystem
    raise errors.BackEndError(
dfvfs.lib.errors.BackEndError: Unable to open file system with error: pyvshadow_volume_open_file_object: unable to open volume. libvshadow_ntfs_volume_header_read_file_io_handle: unable to read NTFS volume header data at offset: 491320770560 (0x7265000000). libvshadow_volume_open_read_ntfs_volume_headers: unable to read backup NTFS volume header. libvshadow_volume_open_read: unable to read NTFS volume headers. libvshadow_volume_open_file_io_handle: unable to read from file IO handle.

```
**Command line and arguments:**
psteal.py --parsers win7_slow --source /my_image.E01 -o xlsx -w /my_timeline.csv --vss_stores all --partitions all

**Source data:**
E01 file, FTK can read it without issues.

**Plaso version:**
plaso - psteal version 20221229

**Operating system Plaso is running on:**
Tested with:
- WSL2 running on Win10: Ubuntu 22.04.1 LTS
- SIFT running on: 20.04.5 LTS (Focal Fossa)

**Comment by blshkv** [comment]
plaso was not in the tree and libvshadow was outdated.
Please remote your custom install, sync and try the latest ebuild:
https://github.com/pentoo/pentoo-overlay/pull/1381
