### ISSUE TITLE
net-analyzer/theHarvester-4.4.4 requires python-dateutil

### ISSUE THREAD

**Issue by ultratensai** [pentoo/pentoo-overlay#1537]
net-analyzer/theHarvester requires dev-python/python-dateutil as a dependency

```
❯ theHarvester -d syngress.com -l 10 -b all
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/theHarvester", line 6, in <module>
    from theHarvester import __main__
  File "/usr/lib/python3.11/site-packages/theHarvester/__main__.py", line 16, in <module>
    from theHarvester.discovery import (
  File "/usr/lib/python3.11/site-packages/theHarvester/discovery/searchhunterhow.py", line 5, in <module>
    from dateutil.relativedelta import relativedelta
ModuleNotFoundError: No module named 'dateutil'
```

**Comment by blshkv** [comment]
my bad, the setup.py is broken (it calls ```from theHarvester.lib.version import version```), so there is no easy way to get deps.
