### ISSUE TITLE
dev-python/pyFFTW-0.13.1: errors compiling cython

### ISSUE THREAD

**Issue by l29ah** [pentoo/pentoo-overlay#1542]
```
Error compiling Cython file:
------------------------------------------------------------
...
IF HAVE_SINGLE_MULTITHREADING:
    fftwf_init_threads()
IF HAVE_LONG_MULTITHREADING:
    fftwl_init_threads()

Py_AtExit(_cleanup)
          ^
------------------------------------------------------------

pyfftw/pyfftw.pyx:756:10: Cannot assign type 'void (void) except *' to 'void (*)(void) noexcept'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void) except *'.
warning: pyfftw/pyfftw.pyx:414:22: Casting a GIL-requiring function into a nogil function circumvents GIL validation
warning: pyfftw/pyfftw.pyx:420:22: Casting a GIL-requiring function into a nogil function circumvents GIL validation
warning: pyfftw/pyfftw.pyx:425:23: Casting a GIL-requiring function into a nogil function circumvents GIL validation
warning: pyfftw/pyfftw.pyx:430:23: Casting a GIL-requiring function into a nogil function circumvents GIL validation
warning: pyfftw/pyfftw.pyx:437:23: Casting a GIL-requiring function into a nogil function circumvents GIL validation

Error compiling Cython file:
------------------------------------------------------------
...

    # count the length of the string and extract it manually rather than using
    # `fftw_export_wisdom_to_string` to avoid calling `free` on the string
    # potentially allocated by a different C library; see #3
    IF HAVE_DOUBLE:
        fftw_export_wisdom(&count_char, <void *>&counter)
                           ^
------------------------------------------------------------

pyfftw/pyfftw.pyx:2053:27: Cannot assign type 'void (*)(char, void *) except *' to 'void (*)(char, void *) noexcept'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (char, void *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
        c_wisdom = <char *>malloc(sizeof(char)*(counter + 1))
        if c_wisdom == NULL:
            raise MemoryError
        # Set the pointers to the string pointers
        cdef intptr_t c_wisdom_ptr = <intptr_t>c_wisdom
        fftw_export_wisdom(&write_char_to_string, <void *>&c_wisdom_ptr)
                           ^
------------------------------------------------------------

pyfftw/pyfftw.pyx:2059:27: Cannot assign type 'void (*)(char, void *) except *' to 'void (*)(char, void *) noexcept'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (char, void *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
        try:
            py_wisdom = c_wisdom
        finally:
            free(c_wisdom)
    IF HAVE_SINGLE:
        fftwf_export_wisdom(&count_char, <void *>&counterf)
                            ^
------------------------------------------------------------

pyfftw/pyfftw.pyx:2067:28: Cannot assign type 'void (*)(char, void *) except *' to 'void (*)(char, void *) noexcept'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (char, void *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
        fftwf_export_wisdom(&count_char, <void *>&counterf)
        c_wisdomf = <char *>malloc(sizeof(char)*(counterf + 1))
        if c_wisdomf == NULL:
            raise MemoryError
        cdef intptr_t c_wisdomf_ptr = <intptr_t>c_wisdomf
        fftwf_export_wisdom(&write_char_to_string, <void *>&c_wisdomf_ptr)
                            ^
------------------------------------------------------------

pyfftw/pyfftw.pyx:2072:28: Cannot assign type 'void (*)(char, void *) except *' to 'void (*)(char, void *) noexcept'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (char, void *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
        try:
            py_wisdomf = c_wisdomf
        finally:
            free(c_wisdomf)
    IF HAVE_LONG:
        fftwl_export_wisdom(&count_char, <void *>&counterl)
                            ^
------------------------------------------------------------

pyfftw/pyfftw.pyx:2079:28: Cannot assign type 'void (*)(char, void *) except *' to 'void (*)(char, void *) noexcept'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (char, void *) except *'.

Error compiling Cython file:
------------------------------------------------------------
...
        fftwl_export_wisdom(&count_char, <void *>&counterl)
        c_wisdoml = <char *>malloc(sizeof(char)*(counterl + 1))
        if c_wisdoml == NULL:
            raise MemoryError
        cdef intptr_t c_wisdoml_ptr = <intptr_t>c_wisdoml
        fftwl_export_wisdom(&write_char_to_string, <void *>&c_wisdoml_ptr)
                            ^
------------------------------------------------------------

pyfftw/pyfftw.pyx:2084:28: Cannot assign type 'void (*)(char, void *) except *' to 'void (*)(char, void *) noexcept'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (char, void *) except *'.
Compiling pyfftw/pyfftw.pyx because it changed.
[1/1] Cythonizing pyfftw/pyfftw.pyx
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pyFFTW-0.13.1/work/pyFFTW-0.13.1/setup.py", line 827, in <module>
    setup_package()
  File "/var/tmp/portage/dev-python/pyFFTW-0.13.1/work/pyFFTW-0.13.1/setup.py", line 824, in setup_package
    setup(**setup_args)
  File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.11/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/usr/lib/python3.11/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.11/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.11/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
    super().run_command(command)
  File "/usr/lib/python3.11/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/usr/lib/python3.11/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/var/tmp/portage/dev-python/pyFFTW-0.13.1/work/pyFFTW-0.13.1/setup.py", line 643, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/lib/python3.11/distutils/command/build_ext.py", line 447, in build_extensions
    self._build_extensions_parallel()
  File "/usr/lib/python3.11/distutils/command/build_ext.py", line 469, in _build_extensions_parallel
    fut.result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.11/site-packages/Cython/Distutils/build_ext.py", line 130, in build_extension
    new_ext = cythonize(
              ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1159, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1326, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: pyfftw/pyfftw.pyx
```

**Comment by blshkv** [comment]
yeap, you need  <cithon-3
https://github.com/pyFFTW/pyFFTW/pull/359

**Comment by ZeroChaos-** [comment]
Restricting to old cython isn't a fix, especially since it looks like upstream fixed it and just hasn't made a release yet.

**Comment by blshkv** [comment]
no, the pull exists since sep, but nobody merged it yet, i.e. the upstream did not approve it.

**Comment by rick-gnous** [comment]
pull request on upstream has been closed, as pyFFTW relies on Cython 3 now. no problem on my side to compile pyFFTW. if the issue is not solved on your side, reopen the ticket
