### ISSUE TITLE
net-proxy/mitmproxy: old dependencies(?)

### ISSUE THREAD

**Issue by Tratoschek** [pentoo/pentoo-overlay#247]
In Gentoo dev-python/cryptography-2.0.2 and dev-python/pyopenssl-17.2.0 were stabilized recently. The mitmproxy ebuild depends on pyopenssl < 17.0 and cryptopgraphy < 1.9 and prevents an update.

Is it possible to update the ebuild? In the [git version](https://github.com/mitmproxy/mitmproxy/blob/master/setup.py) of mitmproxy the dependencies are newer and according to the history of setup.py the dependencies seem to be updated in some automatic way, so it could be possible, that mitmproxy 2.0.2 is already compatible with newer pyopenssl and cryptography.

**Comment by blshkv** [comment]
could you please try again and let me know if it works?

**Comment by Tratoschek** [comment]
Thank you for the fast reaction. Changing only the ebuild dependencies didn't work unfortunately:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyOpenSSL 17.2.0 (/usr/lib64/python3.5/site-packages), Requirement.parse('pyOpenSSL<17.0,>=16.0'), {'mitmproxy'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.5/mitmproxy", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 3030, in <module>
    @_call_aside
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 3014, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 3043, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyOpenSSL<17.0,>=16.0' distribution was not found and is required by mitmproxy
```
Anyway, this check seems to come not directly from mitmproxy. Investigating leads directly to the file `/usr/lib/python-exec/python3.5/mitmproxy` that seems to be somehow generated and checks the dependencies in setup.py(?)

The only check I found in mitmproxy directly is [this one](https://github.com/mitmproxy/mitmproxy/blob/14b33dca5d19afc2427499e25aee8b7439b4b485/mitmproxy/utils/version_check.py), but it is only for outdated versions of pyOpenSSL.

**Comment by blshkv** [comment]
My fault, I fail to test it properly. Fixed
