### ISSUE TITLE
layman not installed anymore

### ISSUE THREAD

**Issue by beta-tester** [pentoo/pentoo-overlay#312]
with the newest pentoo
https://www.pentoo.ch/isos/Pentoo_amd64_hardened/pentoo-full-amd64-hardened-2018.0_RC8.iso
(and https://www.pentoo.ch/isos/Beta/Pentoo_amd64_hardened/pentoo-full-amd64-hardened-2018.0_RC7.2_p20180730.iso)
layman isn't installed anymore.

and when i install layman by doing `sudo emerge layman`,then by using layman there is a missing database.
```
* Warning: an installed db file was not found at: ['/var/lib/layman/cache_930c3ed4a5f89f74fd810585751a06e3.xml']
```

hopefully i was using the commands in a right way...
```
pentoo@pentoo ~ $ sudo emerge layman

 * IMPORTANT: 17 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


These are the packages that would be merged, in reverse order:

Calculating dependencies... done!
[ebuild  N     ] app-portage/layman-2.4.2-r1::gentoo  USE="git gpg mercurial sqlite subversion sync-plugin-portage -bazaar -cvs -darcs (-g-sorcery) -squashfs {-test}" PYTHON_TARGETS="python3_6 (-pypy) -python2_7 -python3_4 -python3_5" 135 KiB
[ebuild  N     ]  dev-vcs/mercurial-4.6.2::gentoo  USE="-bugzilla -emacs -gpg {-test} -tk" PYTHON_TARGETS="python2_7" 6,258 KiB
[ebuild  N     ]  dev-python/pyGPG-0.2::gentoo  PYTHON_TARGETS="python2_7 python3_6 -python3_4 -python3_5" 16 KiB

Total: 3 packages (3 new), Size of downloads: 6,408 KiB

>>> Verifying ebuild manifests
>>> Running pre-merge checks for app-portage/layman-2.4.2-r1
>>> Emerging (1 of 3) dev-python/pyGPG-0.2::gentoo
>>> Emerging (2 of 3) dev-vcs/mercurial-4.6.2::gentoo
>>> Installing (1 of 3) dev-python/pyGPG-0.2::gentoo
>>> Installing (2 of 3) dev-vcs/mercurial-4.6.2::gentoo
>>> Emerging (3 of 3) app-portage/layman-2.4.2-r1::gentoo
>>> Installing (3 of 3) app-portage/layman-2.4.2-r1::gentoo
>>> Recording app-portage/layman in "world" favorites file...
>>> Jobs: 3 of 3 complete                           Load avg: 1.66, 1.10, 0.53

 * Messages for package dev-python/pyGPG-0.2:

 * There may be some python 3 compatibility issues still.
 * Please help debug/fix/report them in github or bugzilla.

 * Messages for package dev-vcs/mercurial-4.6.2:

 * If you want to convert repositories from other tools using convert
 * extension please install correct tool:
 *   dev-vcs/cvs
 *   dev-vcs/darcs
 *   dev-vcs/git
 *   dev-vcs/monotone
 *   dev-vcs/subversion
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * GNU info directory index is up-to-date.

 * IMPORTANT: 17 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

pentoo@pentoo ~ $ sudo layman -a gnuradio

 * Adding overlay...
 * Warning: an installed db file was not found at: ['/var/lib/layman/cache_930c3ed4a5f89f74fd810585751a06e3.xml']
 * Exception: Overlay "gnuradio" does not exist.

 * CLI: Errors occurred processing action add
 * Exception: Overlay "gnuradio" does not exist.

pentoo@pentoo ~ $ sudo layman -sync

 * Fetching remote list...
 * Warning: an installed db file was not found at: ['/var/lib/layman/cache_930c3ed4a5f89f74fd810585751a06e3.xml']
 * Fetch Ok

 * Syncing selected overlay(s)...
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/layman/api.py", line 394, in sync
    odb = db.select(ovl)
  File "/usr/lib64/python3.6/site-packages/layman/dbbase.py", line 260, in select
    raise UnknownOverlayException(overlay)
layman.dbbase.UnknownOverlayException: Exception: Overlay "ync" does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/layman", line 46, in <module>
    main()
  File "/usr/lib64/python3.6/site-packages/layman/cli.py", line 196, in __call__
    result += getattr(self, action[1])()
  File "/usr/lib64/python3.6/site-packages/layman/cli.py", line 281, in Sync
    result = self.api.sync(selection, update_news=True)
  File "/usr/lib64/python3.6/site-packages/layman/api.py", line 401, in sync
    % {'repo': ovl, 'err': error}))
KeyError: 'error'
pentoo@pentoo ~ $ sudo layman -sync-all

 * Fetching remote list...
 * Fetch Ok

 * Syncing selected overlay(s)...
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/layman/api.py", line 394, in sync
    odb = db.select(ovl)
  File "/usr/lib64/python3.6/site-packages/layman/dbbase.py", line 260, in select
    raise UnknownOverlayException(overlay)
layman.dbbase.UnknownOverlayException: Exception: Overlay "ync-all" does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/layman", line 46, in <module>
    main()
  File "/usr/lib64/python3.6/site-packages/layman/cli.py", line 196, in __call__
    result += getattr(self, action[1])()
  File "/usr/lib64/python3.6/site-packages/layman/cli.py", line 281, in Sync
    result = self.api.sync(selection, update_news=True)
  File "/usr/lib64/python3.6/site-packages/layman/api.py", line 401, in sync
    % {'repo': ovl, 'err': error}))
KeyError: 'error'

```

**Comment by blshkv** [comment]
It is no longer required. We hooked to portage

**Comment by blshkv** [comment]
It must be also - - (double) in your last command

**Comment by blshkv** [comment]
I had a second look. So in summary, the correct sequence is the following:
```
emerge layman
layman -S
layman -a gnuradio
```

**Comment by beta-tester** [comment]
thank you very much for helping me...
please excuse my stupidity in gentoo (shame on me)

**Comment by blshkv** [comment]
that's ok. You will like it once you understand the concept and get used to it
