### ISSUE TITLE
jadx: Error load file - update to fix

### ISSUE THREAD

**Issue by 3553x** [pentoo/pentoo-overlay#423]
Hi,
running jadx produces the following error:
```
INFO  - output directory: [SNIP]
INFO  - loading ...
ERROR - jadx error: Error load file: [SNIP].class
jadx.core.utils.exceptions.JadxRuntimeException: Error load file: [SNIP].class
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:126)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:87)
	at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:27)
	at jadx.cli.JadxCLI.main(JadxCLI.java:16)
Caused by: java.io.IOException: Can't read class name from file: [SNIP].class
	at jadx.core.utils.files.InputFile.loadFromClassFile(InputFile.java:180)
	at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:55)
	at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:36)
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:124)
	... 3 common frames omitted
```
This bug was fixed by an author in an update, see:
skylot/jadx#249

I've built the latest version of jadx locally and verified that it fixes the issue.

**Comment by blshkv** [comment]
should be fixed, thanks! Feel free to re-open the issue if it is not
