### ISSUE TITLE
sys-devel/pwndbg: fails to build

### ISSUE THREAD

**Issue by linxon** [pentoo/pentoo-overlay#524]
Demo: https://asciinema.org/a/ZSo0njcnNHm8etAjSiBhbqZPy

**Comment by blshkv** [comment]
Please post the text log, not a video

**Comment by linxon** [comment]
```
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Program received signal SIGTSTP
pwndbg> help rop
Dump ROP gadgets with Jon Salwan's ROPgadget tool.
pwndbg> rop
Saved corefile /tmp/tmpmeui_m23
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/ROPgadget", line 10, in <module>
    import ropgadget
  File "/usr/lib64/python2.7/site-packages/ropgadget/__init__.py", line 10, in <module>
    import ropgadget.binary
  File "/usr/lib64/python2.7/site-packages/ropgadget/binary.py", line 9, in <module>
    from ropgadget.loaders.elf       import *
  File "/usr/lib64/python2.7/site-packages/ropgadget/loaders/__init__.py", line 9, in <module>
    import ropgadget.loaders.elf
  File "/usr/lib64/python2.7/site-packages/ropgadget/loaders/elf.py", line 9, in <module>
    from capstone   import *
ImportError: No module named capstone

pwndbg> quit
linxon@cirno-chan /tmp/linxon-tmp-files $
linxon@cirno-chan /tmp/linxon-tmp-files $
linxon@cirno-chan /tmp/linxon-tmp-files $ ROPgadget --help
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/ROPgadget", line 10, in <module>
    import ropgadget
  File "/usr/lib64/python2.7/site-packages/ropgadget/__init__.py", line 10, in <module>
    import ropgadget.binary
  File "/usr/lib64/python2.7/site-packages/ropgadget/binary.py", line 9, in <module>
    from ropgadget.loaders.elf       import *
  File "/usr/lib64/python2.7/site-packages/ropgadget/loaders/__init__.py", line 9, in <module>
    import ropgadget.loaders.elf
  File "/usr/lib64/python2.7/site-packages/ropgadget/loaders/elf.py", line 9, in <module>
    from capstone   import *
ImportError: No module named capstone
```

**Comment by linxon** [comment]
QA output message:
```
>>> Completed installing dev-libs/capstone-bindings-4.0.1 into /tmp/portage/dev-libs/capstone-bindings-4.0.1/image

 * Final size of build directory: 64028 KiB (62.5 MiB)
 * Final size of installed tree:   9792 KiB ( 9.5 MiB)

 * Verifying compiled files in /usr/lib64/python3.6/site-packages
 * 
 * This package installs one or more Python modules that are not byte-compiled.
 * The following files are missing:
 * 
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/xcore_const.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/xcore_const.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/xcore_const.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/xcore.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/xcore.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/xcore.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/x86_const.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/x86_const.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/x86_const.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/x86.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/x86.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/x86.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/tms320c64x_const.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/tms320c64x_const.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/tms320c64x_const.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/tms320c64x.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/tms320c64x.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/tms320c64x.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/sysz_const.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/sysz_const.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/sysz_const.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/systemz.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/systemz.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/systemz.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/sparc_const.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/sparc_const.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/sparc_const.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/sparc.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/sparc.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/sparc.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/ppc_const.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/ppc_const.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/ppc_const.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/ppc.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/ppc.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/ppc.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/mips_const.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/mips_const.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/mips_const.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/mips.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/mips.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/mips.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/m68k_const.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/m68k_const.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/m68k_const.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/m68k.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/m68k.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/m68k.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/m680x_const.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/m680x_const.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/m680x_const.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/m680x.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/m680x.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/m680x.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/evm_const.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/evm_const.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/evm_const.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/evm.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/evm.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/evm.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/arm_const.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/arm_const.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/arm_const.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/arm64_const.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/arm64_const.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/arm64_const.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/arm64.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/arm64.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/arm64.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/arm.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/arm.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/arm.cpython-36.opt-2.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/__init__.cpython-36.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/__init__.cpython-36.opt-1.pyc
 *   /usr/lib64/python3.6/site-packages/capstone/__pycache__/__init__.cpython-36.opt-2.pyc
 * 
 * Please either fix the upstream build system to byte-compile Python modules
 * correctly, or call python_optimize after installing them.  For more
 * information, see:
 * https://wiki.gentoo.org/wiki/Project:Python/Byte_compiling
 * 
strip: x86_64-pc-linux-gnu-strip --strip-unneeded -N __gentoo_check_ldflags__ -R .comment -R .GCC.command.line -R .note.gnu.gold-version
   /usr/lib64/python3.6/site-packages/capstone/lib/libcapstone.so
   /usr/lib64/python3.6/site-packages/capstone/lib/libcapstone.a

```
