### ISSUE TITLE
yubioath-desktop depends on deprecated qtquickcontrols package.

### ISSUE THREAD

**Issue by dallenwilson** [pentoo/pentoo-overlay#527]
yubioath-desktop failed to update after my latest sync. The error was:
`Project ERROR: Unknown module(s) in QT: quickcontrols2`

I did a quick check with eix and found I had dev-qt/qtquickcontrols installed, noticed the description ended in "(deprecated)", and that a dev-qt/qtquickcontrols2 package was available. I installed that, and was then able to merge yubioath-desktop-5.0.1.

The ebuild currently in the pentoo overlay has "dev-qt/qtquickcontrols:5" as an RDEPEND, but it perhaps should be updated to use qtquickcontrols2 instead.

**Comment by linxon** [comment]
@blshkv https://github.com/pentoo/pentoo-overlay/blob/c9617daab608529023c50b4608a16e64a0dc0290/app-crypt/yubioath-desktop/yubioath-desktop-5.0.1.ebuild#L15-L22


New runtime depends:
 * qt5 — https://github.com/Yubico/yubioath-desktop/blob/f3c9c2b526d01c580c4c0d8b48a8ac41316ec160/yubioath-desktop.pro#L2 
 * [binascii](https://pypi.org/project/pycopy-binascii/) — https://github.com/Yubico/yubioath-desktop/blob/f3c9c2b526d01c580c4c0d8b48a8ac41316ec160/py/yubikey.py#L10

**Comment by blshkv** [comment]
I put a note on binascii dep, please feel free to fix it later. We might need to add a python class for a proper python version control.

**Comment by linxon** [comment]
```bash
linxon@cirno-chan ~ $ yubioath-desktop 
Got library name:  "/usr/lib64/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/yubikey.py\", line 17, in <module>\n    from ykman.driver_ccid import (\n\nImportError: cannot import name 'list_readers'\n"
Unhandled PyOtherSide error: Cannot import module: yubikey (Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 17, in <module>
    from ykman.driver_ccid import (

ImportError: cannot import name 'list_readers'
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.init' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.check_descriptors' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: TypeError: Cannot read property 'success' of undefined undefined
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.get_connected_readers' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: TypeError: Cannot read property 'success' of undefined undefined
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.check_descriptors' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.get_connected_readers' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: TypeError: Cannot read property 'success' of undefined undefined
qml: TypeError: Cannot read property 'success' of undefined undefined
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.check_descriptors' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: TypeError: Cannot read property 'success' of undefined undefined
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.get_connected_readers' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: TypeError: Cannot read property 'success' of undefined undefined
^CSegmentation fault

```

**Comment by linxon** [comment]
>qml: TypeError: Cannot read property 'success' of undefined undefined
^CSegmentation fault

https://github.com/Yubico/yubioath-desktop/issues/488

**Comment by linxon** [comment]
@dallenwilson Hi! Please try to test `app-crypt/yubioath-desktop-5.0.1-r2` with your device and report any problems here
```bash
emaint sync -r pentoo
emerge -avu --changed-slot=y app-crypt/yubioath-desktop
```

**Comment by blshkv** [comment]
@linxon wow, well done!

**Comment by dallenwilson** [comment]
@linxon Works great. Thanks!
