### ISSUE TITLE
Wpscan reports dependency error following a system update

### ISSUE THREAD

**Issue by walterj21** [pentoo/pentoo-overlay#613]
Following a system update, wpscan reports the following dependency error with typhoeus:
```
pentoo@pentoo ~ $ wpscan
Traceback (most recent call last):
	15: from /usr/bin/wpscan:9:in `<main>'
	14: from /usr/bin/wpscan:9:in `load'
	13: from /usr/lib64/ruby/gems/2.5.0/gems/wpscan-3.7.11/bin/wpscan:4:in `<top (required)>'
	12: from /usr/lib64/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	11: from /usr/lib64/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
	10: from /usr/lib64/ruby/site_ruby/2.5.0/rubygems.rb:217:in `try_activate'
	 9: from /usr/lib64/ruby/site_ruby/2.5.0/rubygems.rb:224:in `rescue in try_activate'
	 8: from /usr/lib64/ruby/site_ruby/2.5.0/rubygems/specification.rb:1443:in `activate'
	 7: from /usr/lib64/ruby/site_ruby/2.5.0/rubygems/specification.rb:1461:in `activate_dependencies'
	 6: from /usr/lib64/ruby/site_ruby/2.5.0/rubygems/specification.rb:1461:in `each'
	 5: from /usr/lib64/ruby/site_ruby/2.5.0/rubygems/specification.rb:1475:in `block in activate_dependencies'
	 4: from /usr/lib64/ruby/site_ruby/2.5.0/rubygems/specification.rb:1443:in `activate'
	 3: from /usr/lib64/ruby/site_ruby/2.5.0/rubygems/specification.rb:1461:in `activate_dependencies'
	 2: from /usr/lib64/ruby/site_ruby/2.5.0/rubygems/specification.rb:1461:in `each'
	 1: from /usr/lib64/ruby/site_ruby/2.5.0/rubygems/specification.rb:1472:in `block in activate_dependencies'
/usr/lib64/ruby/site_ruby/2.5.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'typhoeus' (~> 1.3.0) - did find: [typhoeus-1.4.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/home/pentoo/.gem/ruby/2.5.0:/usr/local/lib64/ruby/gems/2.5.0:/usr/lib64/ruby/gems/2.5.0', execute 'gem env' for more information
```
This should be an error with Pentoo dependencies.

**Comment by blshkv** [comment]
the package is required typhoeus-1.3* but Gentoo added 1.4 under the same slot. It must be compatible.

**Comment by blshkv** [comment]
this is the upstream bug, seems fixed in the latest https://github.com/wpscanteam/CMSScanner/blob/master/cms_scanner.gemspec#L27
