### ISSUE TITLE
net-mail/davmail-bin[server]: files missing

### ISSUE THREAD

**Issue by equaeghe** [pentoo/pentoo-overlay#678]
For `net-mail/davmail-bin[server]`, the following code is executed:
https://github.com/pentoo/pentoo-overlay/blob/8c940e279d4b3d7f1d11bd3a9f7836cedfce92e4/net-mail/davmail-bin/davmail-bin-5.5.1.3299.ebuild#L52-L56
However, the `files` directory is missing, so that an error occurs:
```
Traceback (most recent call last):                                                                
  File "/usr/lib/portage/python3.7/doins.py", line 594, in <module>
    sys.exit(main(sys.argv[1:]))                                                                  
  File "/usr/lib/portage/python3.7/doins.py", line 585, in main
    os.path.dirname(source)):                                                                     
  File "/usr/lib/portage/python3.7/doins.py", line 434, in _doins                                                                                                                                   
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.7/doins.py", line 370, in install_file
    return self._ins_runner.run(source, dest_dir)     
  File "/usr/lib/portage/python3.7/doins.py", line 179, in run
    sstat = os.stat(source)                                                                       
FileNotFoundError: [Errno 2] No such file or directory: b'/var/tmp/portage/net-mail/davmail-bin-5.5.1.3299/files/davmail.properties'
```

**Comment by blshkv** [comment]
One of the purpose of this package is to be able to communicate with MS Exchange server interactively during manual PT/forensics. The server part was not even tested and it was just copied from another overlay probably. Should be fixed now.
