### ISSUE TITLE
app-forensics/spiderfoot-3.4 errors on startup

### ISSUE THREAD

**Issue by wofwofwof** [pentoo/pentoo-overlay#740]
when I try to run the /etc/init.d/spiderfoot-daemon it crashes immideately. Manual starting with 
sf -l 127.0.0.1:5001 returns the followowing error:

```
Traceback (most recent call last):
  File "/usr/share/spiderfoot/sf.py", line 52, in <module>
    error_handler = handlers.TimedRotatingFileHandler(
  File "/usr/lib/python3.9/logging/handlers.py", line 208, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding=encoding,
  File "/usr/lib/python3.9/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/spiderfoot/log/spiderfoot.error.log'
```

quick fixing that problems in sf.py:
```
debug_handler = handlers.TimedRotatingFileHandler(
#    "log/spiderfoot.debug.log",
    "/var/log/spiderfoot.debug.log",        
    when="d",
...
log.addHandler(debug_handler)

error_handler = handlers.TimedRotatingFileHandler(
#    "log/spiderfoot.error.log",
    "/var/log/spiderfoot.error.log",    
    when="d",
...
```

reslults into:

```
2021-09-06 11:27:44,338 [INFO] Starting web server at 127.0.0.1:5001 ...
2021-09-06 11:27:44,399 [WARNING]
********************************************************************
Warning: passwd file contains no passwords. Authentication disabled.
Please consider adding authentication to protect this instance!
Refer to https://www.spiderfoot.net/documentation/#security.
********************************************************************


*************************************************************
 Use SpiderFoot by starting your web browser of choice and
 browse to http://127.0.0.1:5001/
*************************************************************

Traceback (most recent call last):
  File "/usr/share/spiderfoot/sf.py", line 605, in <module>
    main()
  File "/usr/share/spiderfoot/sf.py", line 238, in main
    start_web_server(sfWebUiConfig, sfConfig)
  File "/usr/share/spiderfoot/sf.py", line 577, in start_web_server
    cherrypy.quickstart(SpiderFootWebUi(sfWebUiConfig, sfConfig), script_name=web_root, config=conf)
  File "/usr/share/spiderfoot/sfwebui.py", line 86, in __init__
    secure.ContentSecurityPolicy()
AttributeError: module 'secure' has no attribute 'ContentSecurityPolicy'

```

I assume its from dev-python/python-secure, https://github.com/smicallef/spiderfoot/blob/master/requirements.txt lists secure>=0.3.0,<0.4.0, in pentoo the used version is 0.2.1.

Thank you very much for your help!

**Comment by blshkv** [comment]
The package is broken and non keyworded for that reason. Wait for the next release
